# Generated by Django 4.0.6 on 2022-08-19 05:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(null=True)),
                ('account_type', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('balance', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('Adress', models.TextField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('phonenumber', models.CharField(max_length=16)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, null=True)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptdate', models.DateTimeField(default=datetime.datetime.now)),
                ('number', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to='')),
                ('receipttype', models.CharField(max_length=50, null=True)),
                ('amount', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50, null=True)),
                ('pin', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('isActive', models.BooleanField()),
                ('balance', models.BigIntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=8, null=True)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(max_length=15, null=True)),
                ('transaction_charge', models.IntegerField(null=True)),
                ('transactiondateandtime', models.DateTimeField(default=datetime.datetime.now)),
                ('destination_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_b', to='wallet.account')),
                ('origin_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_a', to='wallet.account')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('name', models.CharField(max_length=15, null=True)),
                ('Phone_number', models.CharField(max_length=15, null=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('points', models.IntegerField(null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.IntegerField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('dateandtime', models.DateTimeField(default=datetime.datetime.now)),
                ('loanbalance', models.IntegerField(null=True)),
                ('loanterm', models.IntegerField(null=True)),
                ('payduedate', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=15, null=True)),
                ('date_issue', models.DateTimeField(default=datetime.datetime.now)),
                ('card_type', models.CharField(max_length=14, null=True)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
    ]
