# Generated by Django 4.0.6 on 2022-07-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[], max_length=1, null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('status', models.CharField(max_length=6, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
