# Generated by Django 4.0.6 on 2022-07-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
