# Generated by Django 4.0.6 on 2022-07-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('name', models.CharField(max_length=15, null=True)),
                ('Phone_number', models.CharField(max_length=6, null=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
    ]
