# Generated by Django 4.0.6 on 2022-07-31 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_thirdparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, null=True)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=6)),
            ],
        ),
    ]
