# Generated by Django 4.0.6 on 2022-07-31 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.IntegerField(null=True)),
                ('loan_type', models.CharField(max_length=32, null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('dateandtime', models.DateTimeField(default=datetime.datetime.now)),
                ('loanbalance', models.IntegerField(null=True)),
                ('loanterm', models.IntegerField(null=True)),
                ('payduedate', models.DateTimeField(default=datetime.datetime.now)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
